apiVersion: v1
kind: Pod
metadata:
  name: novapay-signed
  namespace: novapay-demo
spec:
  containers:
    - name: novapay-api
      image: ghcr.io/sonujha78/novapay-supply-chain@sha256:c2aef30af311a4fc3daa87dd1bb52d7b00a475ac176c825094984db0517c087c
